# Generated by Django 3.2.7 on 2021-10-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=254, null=True)),
                ('Region', models.CharField(max_length=254, null=True)),
                ('Population', models.IntegerField()),
                ('Area', models.IntegerField()),
                ('Pop_Density', models.IntegerField()),
                ('Coastline', models.IntegerField()),
                ('Net_migration', models.IntegerField()),
                ('Infant_mortality', models.IntegerField()),
                ('GDP', models.IntegerField()),
                ('Literacy', models.IntegerField()),
                ('Phones', models.IntegerField()),
                ('Arable', models.IntegerField()),
                ('Crops', models.IntegerField()),
                ('Other', models.IntegerField()),
                ('Climate', models.IntegerField()),
                ('Birthrate', models.IntegerField()),
                ('Deathrate', models.IntegerField()),
                ('Agriculture', models.IntegerField()),
                ('Industry', models.IntegerField()),
                ('Service', models.IntegerField()),
            ],
        ),
    ]
