# Generated by Django 3.2.7 on 2021-10-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_countryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryname',
            name='Agriculture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
