# Generated by Django 3.2.7 on 2021-10-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_auto_20211005_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
