# Generated by Django 3.2.7 on 2021-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_countryname_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryname',
            name='Area',
            field=models.IntegerField(null=True),
        ),
    ]
