# Generated by Django 3.2.7 on 2021-10-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_alter_countryname_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryname',
            name='Climate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='Phones',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='Population',
            field=models.IntegerField(null=True),
        ),
    ]
