# Generated by Django 3.2.7 on 2021-10-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_auto_20211005_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryname',
            name='Area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='Climate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='Phones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='Population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
