# Generated by Django 3.2.7 on 2021-10-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_auto_20211005_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryname',
            name='Climate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
