# Generated by Django 3.2.7 on 2021-10-05 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=1)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('description', models.TextField(default='')),
                ('slugs', models.SlugField(default='hbjhjh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=254, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('company_profile', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('requirements', models.CharField(blank=True, max_length=254, null=True)),
                ('benefits', models.CharField(blank=True, max_length=254, null=True)),
                ('telecommuting', models.CharField(blank=True, max_length=100, null=True)),
                ('has_company_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('has_questions', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('required_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('required_education', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('functions', models.CharField(blank=True, max_length=100, null=True)),
                ('fraudulent', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Review')),
                ('reviewer_name', models.CharField(default='', max_length=55)),
                ('reviewer_city', models.CharField(default='', max_length=55)),
                ('reviewer_state', models.CharField(default='', max_length=2)),
                ('email', models.EmailField(default='', max_length=254)),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('review_comment', models.TextField(default='')),
                ('review_slug', models.SlugField(default='')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='ok', max_length=100)),
                ('postion', models.CharField(blank=True, default='ok', max_length=100)),
                ('salary', models.CharField(blank=True, default='ok', max_length=100)),
                ('requrements', models.CharField(blank=True, default='ok', max_length=100)),
                ('job_tpe', models.CharField(blank=True, default='ok', max_length=100)),
                ('job_time', models.CharField(blank=True, default='ok', max_length=100)),
                ('job_info', models.CharField(blank=True, default='ok', max_length=100)),
                ('hr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
