# Generated by Django 3.2.7 on 2021-10-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20211005_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjobs',
            name='benefits',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='employment_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='fraudulent',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='functions',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='has_company_logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='has_questions',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='industry',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='location',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='required_education',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='required_experience',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='requirements',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='salary_range',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyjobs',
            name='telecommuting',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
